# Generated by Django 5.1.8 on 2025-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Qualifications',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
