# Generated by Django 5.1.8 on 2025-04-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(blank=True, choices=[('central_ministry', 'Central Ministry/Department'), ('govt_org', 'Organisation under Government Development'), ('private_sector', 'Private Sector'), ('public_sector', 'Public Sector'), ('state_govt', 'State Government Department')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hash_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('defence', 'Defence'), ('education', 'Education'), ('energy', 'Energy'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('inf_broadcasting', 'Information and Broadcasting'), ('inf_communication', 'Information and Communication Technology')], max_length=50, null=True),
        ),
    ]
