# Generated by Django 5.1.8 on 2025-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_company_category_company_hash_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='audit_organisation_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
