# Generated by Django 5.1.8 on 2025-04-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_company_audit_organisation_name_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='audit_organisation_name',
        ),
    ]
