# Generated by Django 5.1.8 on 2025-04-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_company_name'),
        ('project', '0016_rename_name_project_projectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectname', to='project.project'),
        ),
    ]
