# Generated by Django 5.1.8 on 2025-04-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='Unnamed Company', max_length=255),
        ),
    ]
