# Generated by Django 5.1.8 on 2025-04-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_workorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
