# Generated by Django 5.1.8 on 2025-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_delete_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='audit_type',
            field=models.CharField(blank=True, choices=[('network_infra', 'Network Infrastructure Audit'), ('process_audit', 'Process Audit'), ('red_team', 'Red Team Assessment'), ('source_code', 'Source Code Review'), ('vapt_infra', 'VAPT - Infrastructure'), ('vapt_app', 'VAPT - Application'), ('website', 'Website'), ('web_app', 'Web Application'), ('wireless', 'Wireless Security Audit')], max_length=50, null=True),
        ),
    ]
