# Generated by Django 5.1.8 on 2025-04-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_company_category_company_hash_value_and_more'),
        ('project', '0008_project_audit_mode_project_contact_person_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='audit_organisation_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_projects', to='customers.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='website_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_projects', to='project.prjectscope'),
        ),
    ]
