# Generated by Django 5.1.8 on 2025-04-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_audit_organisation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='testingtype',
            field=models.CharField(choices=[('White Box', 'White Box'), ('Black Box', 'Black Box'), ('Grey Box', 'Grey Box')], default='White Box', max_length=100),
        ),
    ]
