# Generated by Django 5.1.8 on 2025-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_testingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='audit_organisation_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
