# Generated by Django 5.1.8 on 2025-04-19 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_company_audit_organisation_name'),
        ('project', '0011_alter_project_audit_organisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='audit_organisation_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_projects', to='customers.company'),
        ),
    ]
