# Generated by Django 5.1.8 on 2025-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_verify_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='companyname',
        ),
        migrations.AlterField(
            model_name='project',
            name='audit_organisation_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('L1 Report sent', 'Upcoming'), ('L2 Report sent', 'In Progress'), ('Final Report sent', 'Delay'), ('Completed sent', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='testingtype',
            field=models.CharField(choices=[('Level1', 'Level1'), ('Level2', 'Level2'), ('Final Report', 'Final Report')], default='Level1', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectretest',
            name='status',
            field=models.CharField(choices=[('L1 Report sent', 'Upcoming'), ('L2 Report sent', 'In Progress'), ('Final Report sent', 'Delay'), ('Completed sent', 'Completed')], max_length=20),
        ),
    ]
