# Generated by Django 5.1.8 on 2025-04-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_project_companyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='verify_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website_detail',
        ),
    ]
