# Generated by Django 5.1.8 on 2025-04-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_project_verify_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='Projectname',
        ),
    ]
