# Generated by Django 5.1.8 on 2025-04-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_company_name'),
        ('project', '0017_alter_project_projectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='companyname',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
        ),
    ]
