# Generated by Django 5.1.8 on 2025-04-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_vulnerability_poc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='audit_organisation_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projecttype',
        ),
    ]
