# Generated by Django 5.1.8 on 2025-04-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_remove_project_audit_organisation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectexception',
            new_name='project_expected_output',
        ),
        migrations.RemoveField(
            model_name='project',
            name='companyname',
        ),
    ]
