# Generated by Django 5.1.8 on 2025-04-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_remove_company_img'),
        ('project', '0021_rename_projectexception_project_project_expected_output_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_expected_output',
            new_name='projectexception',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Projectname',
        ),
        migrations.AddField(
            model_name='project',
            name='companyname',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
        ),
    ]
