# Generated by Django 5.1.8 on 2025-04-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_rename_project_expected_output_project_projectexception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Projectname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
