# Generated by Django 5.1.8 on 2025-04-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_project_projectname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('central_ministry', 'Central Ministry/Department'), ('govt_org', 'Organisation under Government Development'), ('private_sector', 'Private Sector'), ('public_sector', 'Public Sector'), ('state_govt', 'State Government Department')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('defence', 'Defence'), ('education', 'Education'), ('energy', 'Energy'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('inf_broadcasting', 'Information and Broadcasting'), ('inf_communication', 'Information and Communication Technology')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='verify_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fullname', to=settings.AUTH_USER_MODEL),
        ),
    ]
