# Generated by Django 5.1.8 on 2025-04-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_project_category_project_sector_project_verify_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('L1 Report sent', 'L1 Report sent'), ('L2 Report sent', 'L2 Report sent'), ('Final Report sent', 'Final Report sent'), ('Completed sent', 'Completed sent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectretest',
            name='status',
            field=models.CharField(choices=[('L1 Report sent', 'L1 Report sent'), ('L2 Report sent', 'L2 Report sent'), ('Final Report sent', 'Final Report sent'), ('Completed sent', 'Completed sent')], max_length=20),
        ),
    ]
